version: '3.7'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - ./img/banner-papastream.png:/jellyfin/jellyfin-web/assets/img/banner-light.png:ro
      - ./img/banner-papastream.png:/jellyfin/jellyfin-web/assets/img/banner-dark.png:ro
      - ./img/banner-papastream.png:/jellyfin/jellyfin-web/assets/img/icon-transparent.png:ro
      - ./img/logo-papastream.png:/jellyfin/jellyfin-web/logo.png:ro
      - ./img/logo-papastream.png:/jellyfin/jellyfin-web/favicon.png:ro
    restart: 'unless-stopped'
